lsi: false
safe: true
source: CIPPPPY.GITHUB.IO
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

baseurl: /Anniversary

{{ cippppy.github.io.baseurl }}{{ goodMornings.url }}